import { isLiveEnabled } from "@/lib/live-integrations";
import type { BrandProfile } from "../types";

export const teslaProfile: BrandProfile = {
  key: "tesla",
  displayName: "Tesla",
  dataSource: isLiveEnabled("tesla") ? "live" : "mock",
  capabilities: {
    telemetry: {
      batteryLevel: true,
      batteryRangeKm: true,
      chargeLimit: true,
      chargingState: true,
      chargingRateKw: true,
      timeToFullMinutes: true,
      batteryHealthPct: true,
      cellVoltages: true,
      odometer: true,
      speed: true,
      heading: true,
      location: true,
      interiorTemp: true,
      exteriorTemp: true,
      climateOn: true,
      driverTempSetting: true,
      passengerTempSetting: true,
      hvacMode: true,
      seatHeating: true,
      steeringHeating: true,
      locked: true,
      doorsOpen: true,
      windowsOpen: true,
      trunkOpen: true,
      frunkOpen: true,
      sentryMode: true,
      dashcam: true,
      softwareVersion: true,
      updateAvailable: true,
      tirePressure: true,
      safetyScore: true,
      efficiencyScore: false,
    },
    commands: {
      lock: true,
      unlock: true,
      climateOn: true,
      climateOff: true,
      setClimateTemp: true,
      honk: true,
      flash: true,
      setChargeLimit: true,
      setChargeAmps: true,
      startCharging: true,
      stopCharging: true,
      openChargePort: true,
      closeChargePort: true,
      ventWindows: true,
      closeWindows: true,
      activateSentry: true,
      deactivateSentry: true,
      remoteStart: true,
    },
    history: {
      chargingSessions: true,
      trips: true,
      consumption: true,
      commandLog: true,
      retention: "unlimited",
    },
    refreshModel: "polling",
  },
  // Adapter is a pass-through for mock; live adapter lives in src/lib/tesla/api.ts
  adapter: (raw) => raw,
};
