import { isLiveEnabled } from "@/lib/live-integrations";
import type { BrandProfile } from "../types";

// BMW i4 / iX — mid-high telemetry, no honk/flash, no frunk, no sentry/dashcam.
export const bmwProfile: BrandProfile = {
  key: "bmw",
  displayName: "BMW",
  dataSource: isLiveEnabled("bmw") ? "live" : "mock",
  capabilities: {
    telemetry: {
      batteryLevel: true,
      batteryRangeKm: true,
      chargeLimit: true,
      chargingState: true,
      chargingRateKw: true,
      timeToFullMinutes: true,
      batteryHealthPct: false,
      cellVoltages: false,
      odometer: true,
      speed: true,
      heading: true,
      location: true,
      interiorTemp: true,
      exteriorTemp: true,
      climateOn: true,
      driverTempSetting: true,
      passengerTempSetting: true,
      hvacMode: true,
      seatHeating: true,
      steeringHeating: true,
      locked: true,
      doorsOpen: true,
      windowsOpen: true,
      trunkOpen: true,
      frunkOpen: false,
      sentryMode: false,
      dashcam: false,
      softwareVersion: true,
      updateAvailable: true,
      tirePressure: true,
      safetyScore: false,
      efficiencyScore: true,
    },
    commands: {
      lock: true,
      unlock: true,
      climateOn: true,
      climateOff: true,
      setClimateTemp: true,
      honk: false,
      flash: false,
      setChargeLimit: true,
      setChargeAmps: false,
      startCharging: true,
      stopCharging: true,
      openChargePort: true,
      closeChargePort: true,
      ventWindows: false,
      closeWindows: false,
      activateSentry: false,
      deactivateSentry: false,
      remoteStart: false,
    },
    history: {
      chargingSessions: true,
      trips: true,
      consumption: true,
      commandLog: true,
      retention: "90days",
    },
    refreshModel: "polling",
  },
  adapter: (raw) => raw,
};
