import { isLiveEnabled } from "@/lib/live-integrations";
import type { BrandProfile } from "../types";

// Renault Megane E-Tech — low-mid telemetry, minimal commands.
export const renaultProfile: BrandProfile = {
  key: "renault",
  displayName: "Renault",
  dataSource: isLiveEnabled("renault") ? "live" : "mock",
  capabilities: {
    telemetry: {
      batteryLevel: true,
      batteryRangeKm: true,
      chargeLimit: false,
      chargingState: true,
      chargingRateKw: true,
      timeToFullMinutes: true,
      batteryHealthPct: false,
      cellVoltages: false,
      odometer: true,
      speed: false,
      heading: false,
      location: true,
      interiorTemp: false,
      exteriorTemp: true,
      climateOn: true,
      driverTempSetting: false,
      passengerTempSetting: false,
      hvacMode: false,
      seatHeating: false,
      steeringHeating: false,
      locked: true,
      doorsOpen: false,
      windowsOpen: false,
      trunkOpen: false,
      frunkOpen: false,
      sentryMode: false,
      dashcam: false,
      softwareVersion: false,
      updateAvailable: false,
      tirePressure: false,
      safetyScore: false,
      efficiencyScore: false,
    },
    commands: {
      lock: true,
      unlock: true,
      climateOn: true,
      climateOff: true,
      setClimateTemp: false,
      honk: false,
      flash: false,
      setChargeLimit: false,
      setChargeAmps: false,
      startCharging: true,
      stopCharging: true,
      openChargePort: false,
      closeChargePort: false,
      ventWindows: false,
      closeWindows: false,
      activateSentry: false,
      deactivateSentry: false,
      remoteStart: false,
    },
    history: {
      chargingSessions: true,
      trips: false,
      consumption: false,
      commandLog: false,
      retention: "7days",
    },
    refreshModel: "on-demand",
  },
  adapter: (raw) => raw,
};
