import { isLiveEnabled } from "@/lib/live-integrations";
import type { BrandProfile } from "../types";

// Polestar 2 / 3 — mid telemetry, climate-only commands, no honk/flash/sentry.
export const polestarProfile: BrandProfile = {
  key: "polestar",
  displayName: "Polestar",
  dataSource: isLiveEnabled("polestar") ? "live" : "mock",
  capabilities: {
    telemetry: {
      batteryLevel: true,
      batteryRangeKm: true,
      chargeLimit: true,
      chargingState: true,
      chargingRateKw: true,
      timeToFullMinutes: true,
      batteryHealthPct: true,
      cellVoltages: false,
      odometer: true,
      speed: true,
      heading: false,
      location: true,
      interiorTemp: true,
      exteriorTemp: true,
      climateOn: true,
      driverTempSetting: true,
      passengerTempSetting: false,
      hvacMode: false,
      seatHeating: true,
      steeringHeating: true,
      locked: true,
      doorsOpen: true,
      windowsOpen: false,
      trunkOpen: true,
      frunkOpen: false,
      sentryMode: false,
      dashcam: false,
      softwareVersion: true,
      updateAvailable: true,
      tirePressure: true,
      safetyScore: false,
      efficiencyScore: true,
    },
    commands: {
      lock: true,
      unlock: true,
      climateOn: true,
      climateOff: true,
      setClimateTemp: true,
      honk: false,
      flash: false,
      setChargeLimit: true,
      setChargeAmps: false,
      startCharging: false,
      stopCharging: false,
      openChargePort: false,
      closeChargePort: false,
      ventWindows: false,
      closeWindows: false,
      activateSentry: false,
      deactivateSentry: false,
      remoteStart: false,
    },
    history: {
      chargingSessions: true,
      trips: true,
      consumption: true,
      commandLog: true,
      retention: "90days",
    },
    refreshModel: "polling",
  },
  adapter: (raw) => raw,
};
