import { isLiveEnabled } from "@/lib/live-integrations";
import type { BrandProfile } from "../types";

// Mercedes-EQ (EQE / EQS) — high telemetry, mid commands, no cell voltages.
export const mercedesProfile: BrandProfile = {
  key: "mercedes",
  displayName: "Mercedes-EQ",
  dataSource: isLiveEnabled("mercedes") ? "live" : "mock",
  capabilities: {
    telemetry: {
      batteryLevel: true,
      batteryRangeKm: true,
      chargeLimit: true,
      chargingState: true,
      chargingRateKw: true,
      timeToFullMinutes: true,
      batteryHealthPct: false,
      cellVoltages: false,
      odometer: true,
      speed: true,
      heading: true,
      location: true,
      interiorTemp: true,
      exteriorTemp: true,
      climateOn: true,
      driverTempSetting: true,
      passengerTempSetting: true,
      hvacMode: true,
      seatHeating: true,
      steeringHeating: true,
      locked: true,
      doorsOpen: true,
      windowsOpen: true,
      trunkOpen: true,
      frunkOpen: false,
      sentryMode: false,
      dashcam: false,
      softwareVersion: true,
      updateAvailable: true,
      tirePressure: true,
      safetyScore: false,
      efficiencyScore: true,
    },
    commands: {
      lock: true,
      unlock: true,
      climateOn: true,
      climateOff: true,
      setClimateTemp: true,
      honk: true,
      flash: true,
      setChargeLimit: true,
      setChargeAmps: false,
      startCharging: true,
      stopCharging: true,
      openChargePort: true,
      closeChargePort: true,
      ventWindows: false,
      closeWindows: false,
      activateSentry: false,
      deactivateSentry: false,
      remoteStart: true,
    },
    history: {
      chargingSessions: true,
      trips: true,
      consumption: true,
      commandLog: true,
      retention: "30days",
    },
    refreshModel: "polling",
  },
  adapter: (raw) => raw,
};
