import { isLiveEnabled } from "@/lib/live-integrations";
import type { BrandProfile } from "../types";

// VW ID.3 / ID.4 / ID.7 — mid telemetry, mid commands.
export const vwProfile: BrandProfile = {
  key: "vw",
  displayName: "Volkswagen ID",
  dataSource: isLiveEnabled("vw") ? "live" : "mock",
  capabilities: {
    telemetry: {
      batteryLevel: true,
      batteryRangeKm: true,
      chargeLimit: true,
      chargingState: true,
      chargingRateKw: true,
      timeToFullMinutes: true,
      batteryHealthPct: false,
      cellVoltages: false,
      odometer: true,
      speed: false,
      heading: false,
      location: true,
      interiorTemp: true,
      exteriorTemp: true,
      climateOn: true,
      driverTempSetting: true,
      passengerTempSetting: false,
      hvacMode: false,
      seatHeating: true,
      steeringHeating: false,
      locked: true,
      doorsOpen: true,
      windowsOpen: false,
      trunkOpen: true,
      frunkOpen: false,
      sentryMode: false,
      dashcam: false,
      softwareVersion: true,
      updateAvailable: true,
      tirePressure: true,
      safetyScore: false,
      efficiencyScore: false,
    },
    commands: {
      lock: true,
      unlock: true,
      climateOn: true,
      climateOff: true,
      setClimateTemp: true,
      honk: true,
      flash: true,
      setChargeLimit: true,
      setChargeAmps: false,
      startCharging: true,
      stopCharging: true,
      openChargePort: false,
      closeChargePort: false,
      ventWindows: false,
      closeWindows: false,
      activateSentry: false,
      deactivateSentry: false,
      remoteStart: false,
    },
    history: {
      chargingSessions: true,
      trips: true,
      consumption: true,
      commandLog: false,
      retention: "30days",
    },
    refreshModel: "polling",
  },
  adapter: (raw) => raw,
};
